---
application.conf:
    HOST_IP: 'localhost'
    CB_HOST_URL: 'http://localhost:8091'
    CB_BUCKET_DEDUP_MAIN_NAME: 'ssp_dedup_offset'
    CB_BUCKET_DEDUP_MAIN_PASS: ''
    CB_BUCKET_DEDUP_MAIN_KEY_PREFIX: 'dm_'
    CB_BUCKET_DEDUP_DATA_NAME: 'ssp_web'
    CB_BUCKET_DEDUP_DATA_PASS: ''
    CB_BUCKET_DEDUP_DATA_KEY_PREFIX: ''
    CB_BUCKET_DEDUP_DEDUP_NAME: 'ssp_dedup_key'
    CB_BUCKET_DEDUP_DEDUP_PASS: ''
    CB_BUCKET_DEDUP_DEDUP_KEY_PREFIX: 'dk_'
    CB_BUCKET_DEDUP_OFFSET_NAME: 'ssp_dedup_offset'
    CB_BUCKET_DEDUP_OFFSET_PASS: ''
    CB_BUCKET_DEDUP_OFFSET_KEY_PREFIX: 'do_'
    KAFKA_BROKERS_DEDUP_DELAY: 'localhost:9092'
    KAFKA_TOPIC_DEDUP_DELAY: 'ssp-delayed-events'
    KAFKA_BROKERS_DEDUP_WARNING: 'localhost:9092'
    KAFKA_TOPIC_DEDUP_WARNING: 'ssp-dedup-warning-events'
    KAFKA_BROKERS_DEDUP_FLATTEN: 'localhost:9092'
    KAFKA_TOPIC_DEDUP_FLATTEN: 'ssp-flatten-events'
    KAFKA_BROKERS_DEDUP_CONSUMER: 'localhost:9092'
    KAFKA_TOPIC_DEDUP_CONSUMER: 'ssp-edge-events'
    BATCH_SIZE: '1'
    DEDUP_KEY_TTL: '600s'
    
logback.xml:
    INSIDE_LOG_DIR: '/Users/chenshuai/logs'
    LOG_LEVEL: 'DEBUG'

